### PR TITLE
Assume yes answer to {vg,lv}create

### PR DESCRIPTION
**Pull request by brianjmurrell**
So that tests don't halt waiting for an answer they will never get.

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/486)

### CODE REVIEW

**Comment by jgrund** [comment]
In what situations do we need to be pending on `--yes`?

**Comment by brianjmurrell** [comment]
LVM confirms by prompt of just about anything that looks like it will be overwriting existing data as is the case frequently with device re-use.

**Comment by jgrund** [comment]
> LVM confirms by prompt of just about anything that looks like it will be overwriting existing data as is the case frequently with device re-use.

If that's the case, then there is probably a bug here (or before) that needs to be looked at:

https://github.com/intel-hpdd/intel-manager-for-lustre/blob/27c0e47d1d04434fe78fe81c1531dd071a88d876/chroma-manager/tests/integration/utils/test_blockdevices/test_blockdevice_lvm.py#L43-L57

**Comment by brianjmurrell** [comment]
Here's the [build job](http://jenkins.lotus.hpdd.lab.intel.com/job/manager-for-lustre/3691/) that started the test run that is causing the problem:

```
2018-03-06 10:03:26,321 - test - DEBUG - remote_command[lotus-9vm5.lotus.hpdd.lab.intel.com]: if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk2; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk2 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk2; else exit 0; fi
2018-03-06 10:03:26,608 - test - INFO - clear command command if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk2; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk2 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk2; else exit 0; fi exit_status 0 
output:
  
stderr:
 The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

2018-03-06 10:03:26,609 - test - DEBUG - remote_command[lotus-9vm5.lotus.hpdd.lab.intel.com]: if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3; else exit 0; fi
2018-03-06 10:03:26,902 - test - INFO - clear command command if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3; else exit 0; fi exit_status 0 
output:
  
stderr:
 The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

2018-03-06 10:03:26,902 - test - DEBUG - remote_command[lotus-9vm5.lotus.hpdd.lab.intel.com]: if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk4; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk4 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk4; else exit 0; fi
2018-03-06 10:03:27,255 - test - INFO - clear command command if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk4; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk4 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk4; else exit 0; fi exit_status 0 
output:
  
stderr:
 The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

2018-03-06 10:03:27,255 - test - DEBUG - remote_command[lotus-9vm5.lotus.hpdd.lab.intel.com]: if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5; else exit 0; fi
2018-03-06 10:03:27,658 - test - INFO - clear command command if zpool list zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5; then zpool destroy zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5 && zpool labelclear zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5; else exit 0; fi exit_status 0 
output:
  
stderr:
 The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

2018-03-06 10:03:27,658 - test - DEBUG - remote_command[lotus-9vm5.lotus.hpdd.lab.intel.com]: if lvdisplay /dev/vg_devdiskbyidscsi0QEMU_QEMU_HARDDISK_disk1/lv_devdiskbyidscsi0QEMU_QEMU_HARDDISK_disk1; then lvchange -an /dev/vg_devdiskbyidscsi0QEMU_QEMU_HARDDISK_disk1/lv_devdiskbyidscsi0QEMU_QEMU_HARDDISK_disk1 && lvremove /dev/vg_devdiskbyidscsi0QEMU_QEMU_HARDDISK_disk1/lv_devdiskbyidscsi0QEMU_QEMU_HARDDISK_disk1; else exit 0; fi
```

**Comment by brianjmurrell** [comment]
@jgrund: While I don't disagree that this could actually be a bug in `clear_device_commands()` and needs to be fixed there ultimately, until somebody has time to go figure out what is going wrong there, this bug is causing test runs to hang indefinitely until somebody notices and goes and kills/cancels them.  Nobody has time to do that kind of babysitting.

I would like to suggest landing this in the interim at least so that we don't have that immediate problem.

**Comment by jgrund** [comment]
@brianjmurrell I understand the sentiment, but I don't think we should paper over another error with a change elsewhere.

**Comment by brianjmurrell** [comment]
So, who babysits the test resources, hunts down the runs afflicted by this and kills them off?

What I am proposing is not so much a papering-over since there will be a [ticket](500) open to fix the real issue along with the task of reverting this when it's done.  This is clearly only meant as a stop-gap to prevent the tying up of our test resources and/or the wasting of somebody's time babysitting the test resources due to this issue.

**Pull request merged**
