### PR TITLE
clear_ha script timing out during SSI test reset

### PR DESCRIPTION
**Pull request by tanabarr**
this intermittent failure is certainly related to zfs enabled testing, it is a test Harness related error and very probably not an issue with the product

http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/385/arch=x86_64,distro=el7//consoleFull

```test_hsm_coordinator_enabled_at_fs_creation (tests.integration.shared_storage_configuration.test_hsm.TestHsmCoordinatorControl) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 137, in setUp
    self.reset_cluster()
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 620, in reset_cluster
    self.remote_operations.clear_ha(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 1159, in clear_ha
    self._ssh_address(address, clear_ha_script.read())
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 448, in _ssh_address
    stdout = channel.makefile('rb').read()
  File "/usr/lib/python2.7/site-packages/paramiko/file.py", line 150, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1234, in _read
    return self.channel.recv(size)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 615, in recv
    raise socket.timeout()
timeout: 
```

---
This change is [Reviewable](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/86)

### CODE REVIEW

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1013):

```
test_login (tests.integration.shared_storage_configuration.test_example_api_client.TestExampleApiClient) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 137, in setUp
    self.reset_cluster()
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 620, in reset_cluster
    self.remote_operations.clear_ha(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 1212, in clear_ha
    clear_ha_script.read()))
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 482, in _ssh_address
    stdout = channel.makefile('rb').read()
  File "/usr/lib/python2.7/site-packages/paramiko/file.py", line 150, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1234, in _read
    return self.channel.recv(size)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 615, in recv
    raise socket.timeout()
timeout: 
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1055/arch=x86_64,distro=el7)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1090) has many occurrences.

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1154/arch=x86_64,distro=el7) has many occurrences.

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1162) has many occurrences.

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1216) has many occurrences.

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1226)

**Comment by brianjmurrell** [comment]
There is indication in #244 that this is (as least in some cases) being caused by ZFS (multi-modification perhaps) panicing the node and further ZFS commands hanging.  So the node itself is not dead.  It's just that ZFS commands will continue to timeout as they block in the kernel.

**Comment by tanabarr** [comment]
#244 , which avoids any use of "force" in zpool imports within calls issued by IML, still exhibits this issue where clear_ha script fails due to kernel:PANIC at zfeature.c:294:feature_get_enabled_txg()
. analysing the zfs pool states after the failure gives http://pastebin.intel.com/qolekavewi.sm

**Comment by tanabarr** [comment]
https://jira.hpdd.intel.com/browse/LU-9901
https://github.com/zfsonlinux/zfs/issues/6543

**Comment by brianjmurrell** [comment]
> looks like this corruption is due to performing dd on the disk whilst zpool exists

Do you know that for sure (i.e. you have evidence that the pool is still present when the dd happens) or are you just surmising based on what is happening in #246/#250?

Keep in mind, this `dd` is happening at the start of the test.  This same "clean up" process should be making sure that the pools are in a torn-down state before this `dd` happens.  If they are not, then that's a problem of the tear-down process that is supposed to happen before the `dd`.

**Comment by tanabarr** [comment]
should be resolved with the landing of #325 , related to the occurrence of zfs panics resulting from intertest reset corrupting zpools, investigated in #289

**Pull request closed without merging**
