### PR TITLE
Issue a filesystem stop in tearDown()

### PR DESCRIPTION
**Pull request by brianjmurrell**
During the `ApiTestCaseWithTestReset.setUp()` process
`remote_operations.clear_ha()` is called to clear the Pacemaker
configuration and unmount Lustre targets in this order.

The process of clearing Pacemaker was to stop Pacemaker on each
server, in a serial fashion.  The result of stopping Pacemaker
on the first node of a cluster however meant failing over that
node's targets to the remaining node in the cluster.  Pacemaker
was then stopped on the second node.

In the process of failing over targets on the first node, the
device was unmounted and then mounted on the second node.
However if the MGS had been stopped before OSSes then OSTs
starting up as the second phase of that failover step could take
longer than Pacemaker's 300s limit and end up staring after
Pacemaker (and our test framework) thought it was stopped.
See LU-9925 for more details.

To mitigate all of this, add an orderly stopping of all filesystems
to ApiTestCaseWithTestReset.tearDown() so that targets are all just
shutdown and not failed over, prior to stopping Pacemaker (which
still happens in setUp() but arguably should be part of tearDown()
also).

Also, error check the unmounting of lustre targets and the clear_ha
script execution.

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/299)

### CODE REVIEW

**Comment by tanabarr** [comment]
does this completely remove the MGS as well (because just removing the file system in the UI doesn't)?

**Comment by brianjmurrell** [comment]
> does this completely remove the MGS as well (because just removing the file system in the UI doesn't)?

No.  It doesn't even remove the filesystem.  It just stops it so that the targets stop in an orderly fashion and don't cause [LU-9925](https://jira.hpdd.intel.com/browse/LU-9925).  Having the MGS left behind running should not be a problem as [`remote_operations.clear_ha()`](https://github.com/intel-hpdd/intel-manager-for-lustre/blob/gh%23246/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py#L143) will stop the MGS prior to the next test being run.

> could I please request that you include a pep8 linter in your workflow?

I have the same git commit hooks as everyone else does and that CI uses.  What PEP8 problems do you see with my patch?

**Comment by tanabarr** [comment]
Running pep8...
        /home/share/chroma/chroma-manager/tests/integration/core/remote_operations.py:382:1: W293
 blank line contains whitespace

**Comment by brianjmurrell** [comment]
> /home/share/chroma/chroma-manager/tests/integration/core/remote_operations.py:382:1: W293

That line is not part of this patch.  IIUC/IIRC, our _pre-commit_ hook only applies PEP8 to lines in the patch which is why the PEP8 linter that I am using (indeed that the project is using, including CI) did not pick this up.

Regardless, such things should probably be fixed in a separate patch.

**Comment by jgrund** [comment]
> Regardless, such things should probably be fixed in a separate patch.

+1.

We've discussed this before, but someone should add `yapf` as a pre-commit hook + format the entire codebase with it.

We have lot's of code that is currently piecemeal compliant and is already checked into source control.

Once we have the entire IML repo formatted consistently, then we will enforce AST transforms at pre-commit time and all source code will be auto-formatted consistently.

**Comment by tanabarr** [comment]
ok, yes , agreed if it wasn't part of the patch

**Pull request merged**
