### PR TITLE
Update mdraid and emcpower linux device_plugin components to use device_scanner output

### PR DESCRIPTION
**Pull request by tanabarr**
Currently MDraid and EMCPower implementations still parse _dmsetup table_ command output rather than derive information from the `device-scanner` output.

Convert modules to use the output from the device scanner to move towards an event driven device discovery architecture.

Once completed, legacy tests can be converted and the **device_mapper**  module removed.

Current limitations (things to fix):
- [ ] devices still show up in volumes page when they are components of arrays (seen with zpools and disk partition 9, and mdraid)
- [ ] emcpower device support currently removed
- [x] local filesystem detection is crude and mount points for detected devices are not reported (approach determined to be acceptable given an explicitly formatted block device is not expected to be usable as a location for a lustre target)

---
This change is [Reviewable](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/372)

### CODE REVIEW

**Comment by tanabarr** [comment]
It is difficult to be sure about which devices contain local filesystems without looking at the `fstab` and `mount` output. that output gives us an indication of explicitly mounted filesystems. Even with using `ID_FS_TYPE` and `ID_FS_USAGE` it is still only a best guess.

**Comment by tanabarr** [comment]
I'm searching for udev output from an _emcpower_ system to analyse before I can replace that module.

**Comment by tanabarr** [comment]
https://github.com/intel-hpdd/device-scanner/pull/37 necessary for the alternative approach to `local_filesystems.py`

**Comment by brianjmurrell** [comment]
So, with _systemd_ `/etc/fstab` is actually converted to _systemd_ **mount** units as a transitional step.

Administrators could very well not even have an `/etc/fstab` if they created their **mount** units in _systemd_ directly.  So ultimately, we should not depend on or use `/etc/fstab`.  Instead we should use the _systemd_ units (or any correlation of those to _udev_) directly.

For example:

```
# systemctl status \*.mount
● dev-mqueue.mount - POSIX Message Queue File System
   Loaded: loaded (/usr/lib/systemd/system/dev-mqueue.mount; static; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:44 PST; 2min 48s ago
    Where: /dev/mqueue
     What: mqueue
     Docs: man:mq_overview(7)
           http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
  Process: 482 ExecMount=/bin/mount mqueue /dev/mqueue -t mqueue (code=exited, status=0/SUCCESS)

● dev-hugepages.mount - Huge Pages File System
   Loaded: loaded (/usr/lib/systemd/system/dev-hugepages.mount; static; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:44 PST; 2min 48s ago
    Where: /dev/hugepages
     What: hugetlbfs
     Docs: https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt
           http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
  Process: 490 ExecMount=/bin/mount hugetlbfs /dev/hugepages -t hugetlbfs (code=exited, status=0/SUCCESS)

● sys-kernel-debug.mount - Debug File System
   Loaded: loaded (/usr/lib/systemd/system/sys-kernel-debug.mount; static; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:44 PST; 2min 48s ago
    Where: /sys/kernel/debug
     What: debugfs
     Docs: https://www.kernel.org/doc/Documentation/filesystems/debugfs.txt
           http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
  Process: 487 ExecMount=/bin/mount debugfs /sys/kernel/debug -t debugfs (code=exited, status=0/SUCCESS)

Nov 23 08:27:44 localhost systemd[1]: Mounted Debug File System.

● proc-fs-nfsd.mount - NFSD configuration filesystem
   Loaded: loaded (/usr/lib/systemd/system/proc-fs-nfsd.mount; static; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:44 PST; 2min 48s ago
    Where: /proc/fs/nfsd
     What: nfsd
  Process: 486 ExecMount=/bin/mount nfsd /proc/fs/nfsd -t nfsd (code=exited, status=0/SUCCESS)

Nov 23 08:27:44 localhost systemd[1]: Mounted NFSD configuration filesystem.

● -.mount - /
   Loaded: loaded (/etc/fstab; bad; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:43 PST; 2min 49s ago
    Where: /
     What: /dev/mapper/vg_00-lv_root
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

● run-user-0.mount - /run/user/0
   Loaded: loaded (/proc/self/mountinfo)
   Active: active (mounted) since Thu 2017-11-23 08:30:32 PST; 586ms ago
    Where: /run/user/0
     What: tmpfs

● var-lib-nfs-rpc_pipefs.mount - RPC Pipe File System
   Loaded: loaded (/usr/lib/systemd/system/var-lib-nfs-rpc_pipefs.mount; static; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:45 PST; 2min 47s ago
    Where: /var/lib/nfs/rpc_pipefs
     What: sunrpc
  Process: 714 ExecMount=/bin/mount sunrpc /var/lib/nfs/rpc_pipefs -t rpc_pipefs (code=exited, status=0/SUCCESS)

Nov 23 08:27:45 localhost systemd[1]: Mounting RPC Pipe File System...
Nov 23 08:27:45 localhost systemd[1]: Mounted RPC Pipe File System.

● boot.mount - /boot
   Loaded: loaded (/etc/fstab; bad; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:45 PST; 2min 47s ago
    Where: /boot
     What: /dev/vda1
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 686 ExecMount=/bin/mount /dev/disk/by-uuid/9d18c6f2-d5c6-4891-b4d9-a6b45f080b78 /boot -t ext3 (code=exited, status=0/SUCCESS)

Nov 23 08:27:45 localhost systemd[1]: Mounting /boot...
Nov 23 08:27:45 localhost systemd[1]: Mounted /boot.

● sys-kernel-config.mount - Configuration File System
   Loaded: loaded (/proc/self/mountinfo; static; vendor preset: disabled)
   Active: active (mounted) since Thu 2017-11-23 08:27:43 PST; 2min 49s ago
    Where: /sys/kernel/config
     What: configfs
     Docs: https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt
           http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems

Nov 23 08:27:43 localhost systemd[1]: Mounting Configuration File System...
Nov 23 08:27:43 localhost systemd[1]: Mounted Configuration File System.
```

I can understand the goal of course -- to not present what really shouldn't be considered storage devices intended for Lustre -- to the user.  I don't think we are going to ever be 100% successful in this regard however.  Whether a device is configured as a _systemd_ **mount** unit (either directly or proxied by `/etc/fstab`) is only one heuristic we can use.

Ultimately if the user has LVs or partitions on a "local" disk which he is not using and therefore is not referencing in an `/etc/fstab` or has configured as a _systemd_ **mount** unit those may or may not be intended for Lustre.

I wonder if we need some kind of user control here to customise the filtering-out of devices.

**Pull request merged**
