### PR TITLE
backtrace: Communications error with lotus-58vm17.lotus.hpdd.lab.intel.com because session terminated

### PR DESCRIPTION
**Pull request by tanabarr**
Observed in a [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/615):
```
test_mdt0_undeletable (tests.integration.shared_storage_configuration.test_filesystem_dne.TestFilesystemDNE) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py", line 189, in test_mdt0_undeletable
    filesystem = self._create_filesystem(3)
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py", line 69, in _create_filesystem
    'conf_params': {}})
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 432, in create_filesystem
    timeout = LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/', u'/api/job/44/', u'/api/job/45/', u'/api/job/46/', u'/api/job/47/', u'/api/job/48/', u'/api/job/49/'], u'complete': True, u'created_at': u'2017-07-09T06:19:30.135014+00:00', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': u'9', u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/39/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': u'4', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/9/', u'id': u'9', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': u'1', u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/13/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': u'1', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/6/', u'id': u'6', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': u'2', u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/41/', u'volume_nodes': [{u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': u'5', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/10/', u'id': u'10', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': u'3', u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/37/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': u'3', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/8/', u'id': u'8', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': u'4', u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/16/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': u'2', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/7/', u'id': u'7', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': u'5', u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/39/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': u'4', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/9/', u'id': u'9', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': u'1', u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/13/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': u'1', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/6/', u'id': u'6', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': u'2', u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/41/', u'volume_nodes': [{u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': u'5', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/10/', u'id': u'10', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': u'3', u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/37/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': u'3', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/8/', u'id': u'8', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': u'4', u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/16/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': u'2', u'host_label': u'lotus-54vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/7/', u'id': u'7', u'host_label': u'lotus-54vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': u'5', u'size': u'10737418240'}
COMMAND 9: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/', u'/api/job/44/', u'/api/job/45/', u'/api/job/46/', u'/api/job/47/', u'/api/job/48/', u'/api/job/49/'], u'complete': True, u'created_at': u'2017-07-09T06:19:30.135014+00:00', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': u'9', u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}

Job 43 Errored (Start target testfs-MDT0001):
{u'commands': [u'/api/command/9/'], u'write_locks': [{u'locked_item_content_type_id': 92, u'locked_item_id': 3, u'locked_item_uri': u'/api/target/3/', u'resource_uri': u''}], u'description': u'Start target testfs-MDT0001', u'read_locks': [{u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}], u'class_name': u'StartTargetJob', u'step_results': {u'/api/step/86/': None}, u'created_at': u'2017-07-09T06:19:30.471890+00:00', u'modified_at': u'2017-07-09T06:19:30.471857+00:00', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/86/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/40/'], u'id': u'43', u'resource_uri': u'/api/job/43/'}

Step 86 failed:
step_count: 1
console: modprobe osd_zfs: 0


modprobe zfs: 0


modprobe osd_zfs: 0


modprobe zfs: 0


zpool export zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15: 1

cannot open 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15': no such pool


description: Mounting target testfs-MDT0001 on node lotus-54vm15.lotus.hpdd.lab.intel.com
class_name: MountOrImportStep
backtrace: Communications error with lotus-54vm15.lotus.hpdd.lab.intel.com because session terminated
created_at: 2017-07-09T06:21:27.825316+00:00
args: {u'active_volume_node': [u'lotus-54vm15.lotus.hpdd.lab.intel.com', u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15/testfs-MDT0001', u'zfs'], u'start_target': True, u'target': u'testfs-MDT0001', u'inactive_volume_nodes': [[u'lotus-54vm16.lotus.hpdd.lab.intel.com', u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15/testfs-MDT0001', u'zfs']]}
modified_at: 2017-07-09T06:23:12.600528+00:00
step_index: 0
state: failed
result: 
resource_uri: /api/step/86/
id: 86
log: 

Job 44 Errored (Start target testfs-MDT0000):
{u'commands': [u'/api/command/9/'], u'write_locks': [{u'locked_item_content_type_id': 92, u'locked_item_id': 2, u'locked_item_uri': u'/api/target/2/', u'resource_uri': u''}], u'description': u'Start target testfs-MDT0000', u'read_locks': [{u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}], u'class_name': u'StartTargetJob', u'step_results': {u'/api/step/92/': None}, u'created_at': u'2017-07-09T06:19:30.477649+00:00', u'modified_at': u'2017-07-09T06:19:30.477615+00:00', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/92/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/42/'], u'id': u'44', u'resource_uri': u'/api/job/44/'}

Step 92 failed:
step_count: 1
console: 
description: Mounting target testfs-MDT0000 on node lotus-54vm15.lotus.hpdd.lab.intel.com
class_name: MountOrImportStep
backtrace: Communications error with lotus-54vm15.lotus.hpdd.lab.intel.com because session terminated
created_at: 2017-07-09T06:21:36.748852+00:00
args: {u'active_volume_node': [u'lotus-54vm15.lotus.hpdd.lab.intel.com', u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'linux'], u'start_target': True, u'target': u'testfs-MDT0000', u'inactive_volume_nodes': [[u'lotus-54vm16.lotus.hpdd.lab.intel.com', u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'linux']]}
modified_at: 2017-07-09T06:23:12.670266+00:00
step_index: 0
state: failed
result: 
resource_uri: /api/step/92/
id: 92
log: 

Job 45 Errored (Start target testfs-MDT0002):
{u'commands': [u'/api/command/9/'], u'write_locks': [{u'locked_item_content_type_id': 92, u'locked_item_id': 4, u'locked_item_uri': u'/api/target/4/', u'resource_uri': u''}], u'description': u'Start target testfs-MDT0002', u'read_locks': [{u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}], u'class_name': u'StartTargetJob', u'step_results': {u'/api/step/83/': None}, u'created_at': u'2017-07-09T06:19:30.483366+00:00', u'modified_at': u'2017-07-09T06:19:30.483332+00:00', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/83/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/41/'], u'id': u'45', u'resource_uri': u'/api/job/45/'}

Step 83 failed:
step_count: 1
console: modprobe osd_zfs: 0


modprobe zfs: 0


modprobe osd_zfs: 0


modprobe zfs: 0


zpool export zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11: 1

cannot open 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11': no such pool

modprobe osd_zfs: 0


modprobe zfs: 0


modprobe osd_zfs: 0


modprobe zfs: 0


zpool import zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11: 1

cannot import 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11': a pool with that name already exists
use the form 'zpool import <pool | id> <newpool>' to give it a new name

zpool list -H -o name: 0
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15


zpool get -Hp all zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11: 0
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	size	10670309376	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	capacity	0%	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	altroot	-	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	health	ONLINE	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	guid	1289176912314130593	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	version	-	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	bootfs	-	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	delegation	on	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	autoreplace	off	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	cachefile	-	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	failmode	panic	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	listsnapshots	off	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	autoexpand	off	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	dedupditto	0	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	dedupratio	1.00x	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	free	10668459008	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	allocated	1850368	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	readonly	off	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	ashift	0	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	comment	-	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	expandsize	-	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	freeing	0	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	fragmentation	0%	-
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	leaked	0	default
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@async_destroy	enabled	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@empty_bpobj	active	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@lz4_compress	active	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@spacemap_histogram	active	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@enabled_txg	active	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@hole_birth	active	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@extensible_dataset	enabled	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@embedded_data	active	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@bookmarks	enabled	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@filesystem_limits	enabled	local
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11	feature@large_blocks	enabled	local


modprobe osd_zfs: 0


modprobe zfs: 0


zpool export zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11: 0



description: Mounting target testfs-MDT0002 on node lotus-54vm15.lotus.hpdd.lab.intel.com
class_name: MountOrImportStep
backtrace: Communications error with lotus-54vm15.lotus.hpdd.lab.intel.com because session terminated
created_at: 2017-07-09T06:21:26.773568+00:00
args: {u'active_volume_node': [u'lotus-54vm15.lotus.hpdd.lab.intel.com', u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/testfs-MDT0002', u'zfs'], u'start_target': True, u'target': u'testfs-MDT0002', u'inactive_volume_nodes': [[u'lotus-54vm16.lotus.hpdd.lab.intel.com', u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/testfs-MDT0002', u'zfs']]}
modified_at: 2017-07-09T06:23:12.639914+00:00
step_index: 0
state: failed
result: 
resource_uri: /api/step/83/
id: 83
log: 


--------------------- >> end captured stdout << ----------------------
```

This was also [reported in Jira back in Feb. 2017](https://jira.hpdd.intel.com/browse/HYD-7169).

Is this the type of problem that 2f788b9f6f4df6aafca37a42465422e425bed068 is trying to address or is this something different?

---
This change is [Reviewable](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/127)

### CODE REVIEW

**Comment by tanabarr** [comment]
my mistake, commit message for 9d0fb05 should be "add fetch help to try to catch issue #127 "

**Comment by tanabarr** [comment]
Fetch help triggered on SSI build 1007, pausing at the time when MountOrImportStep failed.

Manager shows that Create flesystem command failed with the following console output:
```
Failed to start target testfs-OST0001_695e69
```
The MountOrImportStep was called to mount on active node 5 and export on inactive node 6.

Details from the active node:
```
[root@lotus-45vm5 ~]# crm_mon -1
Stack: corosync
Current DC: lotus-45vm5.lotus.hpdd.lab.intel.com (version 1.1.16-12.el7-94ff4df) - partition with quorum
Last updated: Wed Aug 23 08:44:55 2017
Last change: Tue Aug 22 13:52:06 2017 by root via crm_resource on lotus-45vm5.lotus.hpdd.lab.intel.com

2 nodes configured
5 resources configured (1 DISABLED)

Online: [ lotus-45vm5.lotus.hpdd.lab.intel.com lotus-45vm6.lotus.hpdd.lab.intel.com ]

Active resources:

 st-fencing     (stonith:fence_chroma): Started lotus-45vm5.lotus.hpdd.lab.intel.com
 MGS_ba5c50     (ocf::chroma:Target):   Started lotus-45vm5.lotus.hpdd.lab.intel.com
 testfs-MDT0000_746776  (ocf::chroma:Target):   Started lotus-45vm5.lotus.hpdd.lab.intel.com
 testfs-OST0000_e97e19  (ocf::chroma:Target):   Started lotus-45vm5.lotus.hpdd.lab.intel.com
```
Note that OST0001 is disabled in pacemaker after number of failed retries to start the target.

```
[root@lotus-45vm5 ~]#mount
...
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5 on /zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5 type zfs (rw,xattr,noacl)
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5/MGS on /mnt/MGS type lustre (ro)
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1 on /zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1 type zfs (rw,xattr,noacl)
zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1/testfs-MDT0000 on /mnt/testfs-MDT0000 type lustre (ro)
/dev/sde on /mnt/testfs-OST0000 type lustre (ro)
...
```

No lustre targets are mounted on node 6 at the time.

**Comment by brianjmurrell** [comment]
[This](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1166) looks like another, but agent log corruption prevents us from knowing for sure.

**Comment by tanabarr** [comment]
no longer relevant with reactive architecture changes

**Pull request closed without merging**
