### PR TITLE
Revert "Rename "linux" to "ldiskfs""

### PR DESCRIPTION
**Pull request by brianjmurrell**
This reverts commit e314b162025164f070f202637325beb34566303e.

This needs a bit more work to be completely comprehensive.

---
This change is [Reviewable](https://reviewable.io/reviews/intel-hpdd/intel-manager-for-lustre/276)

### CODE REVIEW

**Comment by brianjmurrell** [comment]
> I'm not sure I understand the benefit of this revert, could you offer some description as to why you think it's necessary

Because it's incomplete.  It's incoherent with the use of _linux_ throughout _iml-common_ and as such might lead to **ldiskfs != linux** comparison mismatches where things that should happen for _ldiskfs_ block devices don't because the name is still _linux_ in _iml-common_.

I think for safety this should revert back to the previous, well-known behaviour until another pass at this can be done taking _iml-common_ into account.

**Comment by jgrund** [comment]
> Because it's incomplete. It's incoherent with the use of linux throughout iml-common and as such might lead to ldiskfs != linux comparison mismatches where things that should happen for ldiskfs block devices don't because the name is still linux in iml-common.

Just so I have a point of reference, can you paste a link to an example of this?

**Comment by brianjmurrell** [comment]
> Just so I have a point of reference, can you paste a link to an example of this?

Do you mean an example of the [use of _linux_ where it really should mean _ldiskfs_'](
https://github.com/intel-hpdd/iml-common/blob/master/iml_common/blockdevices/blockdevice_linux.py#L16-L17)?

**Comment by jgrund** [comment]
Given this patch seems more correct, any reason we don't just update iml-common to replace `linux` with `ldiskfs`?

**Comment by jgrund** [comment]
Also, beyond nomenclature, is there any overlap between this change and iml-common codewise?

**Comment by brianjmurrell** [comment]
> Given this patch seems more correct, any reason we don't just update iml-common to replace linux with ldiskfs?

Ultimatley, no.  That would be the best long-term solution.  I am just questioning if this is the right time (i.e. in the release cycle) to embark upon this kind of change, particularly given how unstable testing already is.

> Also, beyond nomenclature, is there any overlap between this change and iml-common codewise?

I'm not sure, TBH, which is why I am taking the conservative approach and undoing what looks to be a partial change.

**Comment by brianjmurrell** [comment]
> iml-common seems to be consistent with this nomenclature

How is _iml-common_ consistent when everything it does with what is actually _ldiskfs_ filesystems uses _linux_ in the name instead of _ldiskfs_, such as [class BlockDeviceLinux(BlockDevice):](
https://github.com/intel-hpdd/iml-common/blob/master/iml_common/blockdevices/blockdevice_linux.py#L16-L17) and everything that cascades down from that?

**Comment by tanabarr** [comment]
BlockDeviceLinux refers to the underlying block devices of the type "linux" e.g. /dev/sda, they support hosting filesystems of type "ldiskfs" https://github.com/intel-hpdd/iml-common/blob/master/iml_common/blockdevices/blockdevice_linux.py#L79 which are represented by FileSystemLdiskfs objects

**Comment by brianjmurrell** [comment]
> BlockDeviceLinux refers to the underlying block devices of the type "linux" e.g. /dev/sda

That nomenclature is still wrong.  _/dev/sda_ is not a **Linux** device.  It's a disk.  We should probably clear up that nomenclature as well.

**Comment by brianjmurrell** [comment]
Closing this as the patch it's reverting is not being seen as a risk.

**Pull request closed without merging**
